"""Focused, rule-based SEC HTML filing extraction for Lambda."""
import json
import re
from socket import timeout as SocketTimeout
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
from business_summarizer import summarize_business_section, summarize_risk_factors_section
from regex_helpers import (
    extract_business_section,
    extract_first_number_after_label,
    extract_first_number_between,
    extract_inline_xbrl_fact,
    extract_inline_xbrl_text,
    extract_period_end_date,
    extract_risk_factors_section,
    extract_scale,
    extract_title,
    html_to_text,
    looks_like_sec_filing,
    remove_form_suffix,
)

METRIC_TAGS = {
    "revenue": [
        "Revenues",
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "SalesRevenueNet",
    ],
    "cost_of_revenue": ["CostOfRevenue", "CostOfGoodsAndServicesSold", "CostOfGoodsSold"],
    "gross_profit": ["GrossProfit"],
    "operating_expenses": ["OperatingExpenses"],
    "operating_income": ["OperatingIncomeLoss"],
    "net_income": ["NetIncomeLoss", "ProfitLoss"],
    "diluted_eps": ["EarningsPerShareDiluted"],
    "operating_cash_flow": ["NetCashProvidedByUsedInOperatingActivities"],
    "capex": ["PaymentsToAcquirePropertyPlantAndEquipment"],
    "dividends": ["PaymentsOfDividends", "PaymentsOfDividendsCommonStock", "PaymentsOfOrdinaryDividends"],
    "repurchases": ["PaymentsForRepurchaseOfCommonStock", "PaymentsForRepurchaseOfEquity"],
    "cash": ["CashAndCashEquivalentsAtCarryingValue"],
    "total_assets": ["Assets"],
    "total_liabilities": ["Liabilities"],
    "long_term_debt": ["LongTermDebtNoncurrent", "LongTermDebt"],
    "shareholders_equity": [
        "StockholdersEquity",
        "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
    ],
    "shares": ["WeightedAverageNumberOfDilutedSharesOutstanding"],
}

PER_SHARE_METRICS = {"diluted_eps"}
FETCH_TIMEOUT_SECONDS = 30
ISSUER_MIRROR_TIMEOUT_SECONDS = 8

TEXT_METRIC_LABELS = {
    "revenue": ("Total net sales",),
    "cost_of_revenue": ("Total cost of sales", "Cost of revenue"),
    "gross_profit": ("Gross margin", "Gross profit"),
    "operating_expenses": ("Total operating expenses",),
    "operating_income": ("Operating income",),
    "net_income": ("Net income",),
    "operating_cash_flow": ("Cash generated by operating activities",),
    "capex": ("Payments for acquisition of property, plant and equipment",),
    "dividends": ("Payments for dividends and dividend equivalents",),
    "repurchases": ("Repurchases of common stock",),
    "cash": ("Cash and cash equivalents",),
    "total_assets": ("Total assets",),
    "total_liabilities": ("Total liabilities",),
    "shareholders_equity": ("Total shareholders’ equity", "Total shareholders' equity", "Total shareholders&#8217; equity"),
}


def extract_company(html):
    company = extract_inline_xbrl_text(html, "dei", "EntityRegistrantName")
    return company or remove_form_suffix(extract_title(html))


def fetch_html(url, timeout_seconds=FETCH_TIMEOUT_SECONDS):
    request = Request(
        url,
        headers={
            "User-Agent": "sec-filings-analyzer/1.0 ishasingh2893@gmail.com",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
            "Connection": "close",
        },
    )
    try:
        with urlopen(request, timeout=timeout_seconds) as response:
            return response.read(12 * 1024 * 1024).decode("utf-8", errors="replace")
    except (SocketTimeout, TimeoutError) as exc:
        raise TimeoutError(
            "Timed out while fetching the filing HTML. Try the SEC EDGAR archive URL for this filing instead of an issuer-hosted mirror."
        ) from exc
    except HTTPError as exc:
        raise ValueError(f"Unable to fetch filing HTML: HTTP {exc.code}.") from exc
    except URLError as exc:
        raise ValueError(f"Unable to fetch filing HTML: {exc.reason}.") from exc


def fetch_json(url):
    request = Request(
        url,
        headers={
            "User-Agent": "sec-filings-analyzer/1.0 ishasingh2893@gmail.com",
            "Accept": "application/json",
        },
    )
    with urlopen(request, timeout=FETCH_TIMEOUT_SECONDS) as response:
        return json.load(response)


def latest_sec_10k_url_for_cik(cik):
    padded_cik = str(int(cik)).zfill(10)
    submissions = fetch_json(f"https://data.sec.gov/submissions/CIK{padded_cik}.json")
    recent = submissions.get("filings", {}).get("recent", {})
    for index, form in enumerate(recent.get("form", [])):
        if form == "10-K":
            accession = recent["accessionNumber"][index].replace("-", "")
            document = recent["primaryDocument"][index]
            archive_cik = str(int(cik))
            return f"https://www.sec.gov/Archives/edgar/data/{archive_cik}/{accession}/{document}"
    return ""


def fallback_sec_url_for_input_url(url):
    cik = extract_cik_from_url(url)
    if not cik:
        return ""
    return latest_sec_10k_url_for_cik(cik)


def extract_cik_from_url(url):
    for pattern in (r"/data/(\d{1,10})/", r"CIK[-_]?0*(\d{1,10})", r"cik=(\d{1,10})"):
        match = re.search(pattern, url, re.I)
        if match:
            return match.group(1)
    return ""


def extract_period(html, text):
    return extract_inline_xbrl_text(html, "dei", "DocumentPeriodEndDate") or extract_period_end_date(text)


def parse_metric_value(value):
    return float(value.replace(",", "").replace("(", "-").replace(")", ""))


def extract_xbrl_metric(html, tags, key):
    for tag in tags:
        match = extract_inline_xbrl_fact(html, "us-gaap", tag)
        if not match:
            continue
        value = parse_metric_value(match.group(1))
        scale_match = extract_scale(html, "us-gaap", tag)
        value *= 10 ** int(scale_match.group(1)) if scale_match else 1
        if key in PER_SHARE_METRICS:
            return value
        return abs(value) / 1_000_000 if key in {"capex", "dividends", "repurchases"} else value / 1_000_000
    return None


def extract_text_metric(text, key):
    if key == "long_term_debt":
        value = extract_first_number_between(text, "Non-current liabilities:", "Term debt", "Total non-current liabilities")
        return parse_metric_value(value) if value else None
    if key == "shares":
        value = extract_first_number_between(text, "Shares used in computing earnings per share:", "Diluted", "See accompanying")
        return parse_metric_value(value) / 1_000 if value else None
    if key == "diluted_eps":
        value = extract_first_number_between(text, "Earnings per share:", "Diluted", "Shares used in computing earnings per share:")
        return parse_metric_value(value) if value else None
    for label in TEXT_METRIC_LABELS.get(key, ()):
        value = extract_first_number_after_label(text, label)
        if value:
            parsed = parse_metric_value(value)
            return abs(parsed) if key in {"capex", "dividends", "repurchases"} else parsed
    return None


def extract_metric(html, text, key, tags):
    return extract_xbrl_metric(html, tags, key) or extract_text_metric(text, key)


def extract_metrics(html, text):
    metrics = {key: extract_metric(html, text, key, tags) for key, tags in METRIC_TAGS.items()}
    if metrics.get("capex") is not None:
        metrics["capex"] = abs(metrics["capex"])
    if metrics.get("operating_cash_flow") is not None and metrics.get("capex") is not None:
        metrics["free_cash_flow"] = metrics["operating_cash_flow"] - metrics["capex"]
    else:
        metrics["free_cash_flow"] = None
    if metrics.get("dividends") is not None or metrics.get("repurchases") is not None:
        metrics["capital_return"] = (metrics.get("dividends") or 0) + (metrics.get("repurchases") or 0)
    else:
        metrics["capital_return"] = None
    return metrics


def extract_sections(text):
    sections = {"document": text[:4000]}
    business = summarize_business_section(extract_business_section(text))
    if business:
        sections["business"] = business
    risk_factors = summarize_risk_factors_section(extract_risk_factors_section(text))
    if risk_factors:
        sections["risk_factors"] = risk_factors
    return sections


def analyze_html(url):
    try:
        initial_timeout = FETCH_TIMEOUT_SECONDS if "sec.gov/Archives/" in url else ISSUER_MIRROR_TIMEOUT_SECONDS
        html = fetch_html(url, initial_timeout)
    except (TimeoutError, ValueError):
        fallback_url = fallback_sec_url_for_input_url(url)
        if not fallback_url:
            raise
        html = fetch_html(fallback_url)
    text = html_to_text(html)
    if not looks_like_sec_filing(text):
        raise ValueError("The URL does not appear to be an SEC 10-Q or 10-K filing.")
    return {
        "company": extract_company(html),
        "period": extract_period(html, text),
        "metrics": extract_metrics(html, text),
        "sections": extract_sections(text),
    }
