import assert from 'node:assert/strict';
import { test } from 'node:test';
import { DOMParser } from 'linkedom';
import { makeFilingChunks, retrieveBm25, retrieveGroundedChunks } from '../lib/bm25.ts';
import { analyze, valuation, demo, readFile } from '../lib/filing.ts';
globalThis.DOMParser=DOMParser;
const text='FORM 10-K\nItem 1. Business\n'+('Our company develops enterprise software and provides support services to customers across multiple industries. '.repeat(5))+'\nItem 1A. Risk factors\n'+('Competition and customer concentration could adversely affect our business and financial results. '.repeat(5));
const context=(id,start,end,extra='')=>`<xbrli:context id="${id}"><xbrli:entity>${extra}</xbrli:entity><xbrli:period>${start?`<xbrli:startDate>${start}</xbrli:startDate><xbrli:endDate>${end}</xbrli:endDate>`:`<xbrli:instant>${end}</xbrli:instant>`}</xbrli:period></xbrli:context>`;
const fact=(tag,value,c='annual',scale='6',unit='usd',extra='')=>`<ix:nonFraction name="us-gaap:${tag}" contextref="${c}" unitref="${unit}" scale="${scale}" ${extra}>${value}</ix:nonFraction>`;
function html(extra=''){return `<html><body><ix:nonNumeric name="dei:EntityRegistrantName" contextref="annual">Test Company</ix:nonNumeric><ix:nonNumeric name="dei:DocumentPeriodEndDate" contextref="annual">2025-12-31</ix:nonNumeric><xbrli:unit id="usd"><xbrli:measure>iso4217:USD</xbrli:measure></xbrli:unit><xbrli:unit id="shares"><xbrli:measure>xbrli:shares</xbrli:measure></xbrli:unit>${context('annual','2025-01-01','2025-12-31')}${context('old','2024-01-01','2024-12-31')}${context('quarter','2025-10-01','2025-12-31')}${context('segment','2025-01-01','2025-12-31','<xbrldi:explicitMember dimension="Test">Segment</xbrldi:explicitMember>')}${fact('NetIncomeLoss','90','old')}${fact('NetIncomeLoss','50','quarter')}${fact('NetIncomeLoss','20','segment')}${fact('NetIncomeLoss','120')}${fact('Revenues','1,200')}${fact('WeightedAverageNumberOfDilutedSharesOutstanding','10','annual','6','shares')}${extra}</body></html>`}
test('selects current consolidated annual figures and normalized units',()=>{const r=analyze({text,html:html()},'test.htm');assert.equal(r.company,'Test Company');assert.equal(r.metrics.income.value,120);assert.equal(r.metrics.revenue.value,1200);assert.equal(r.metrics.shares.value,10);assert.equal(r.metrics.cash.value,null);assert.equal(r.excerpts.length,2)});
test('conflicting facts stay missing',()=>{const r=analyze({text,html:html(fact('NetIncomeLoss','121'))},'test.htm');assert.equal(r.metrics.income.value,null)});
test('no fabricated metrics for unstructured documents',()=>{const r=analyze({text},'test.txt');assert.ok(Object.values(r.metrics).every(m=>m.value===null))});
test('rejects short scans and non-filings',()=>{assert.throws(()=>analyze({text:'10-K'},'scan.pdf'),/OCR/);assert.throws(()=>analyze({text:'This is an unrelated document. '.repeat(30)},'note.txt'),/annual filing/)});
test('earnings valuation and invalid inputs',()=>{assert.deepEqual(valuation(120,10,'15','25'),{low:180,high:300,error:''});assert.equal(valuation(null,10,'15','25'),null);assert.ok(valuation(-20,10,'15','25').error);assert.ok(valuation(20,0,'15','25').error);assert.ok(valuation(20,10,'25','15').error);assert.ok(valuation(20,10,'','15').error);assert.equal(valuation(demo().metrics.income.value,demo().metrics.shares.value,'15','25').low,90)});
test('file validation',async()=>{await assert.rejects(readFile(new File(['hello'],'file.exe'),()=>{}),/Choose a PDF/);await assert.rejects(readFile({size:31*1024*1024,name:'big.pdf'},()=>{}),/30 MB/)});
test('table candidates require units and consolidated context',()=>{const table='\nCONSOLIDATED STATEMENTS OF OPERATIONS\nUSD in millions\n2025 2024 2023\nNet income 120 100 80\n';const r=analyze({text:text+table},'report.txt');assert.equal(r.metrics.income.value,120);assert.match(r.metrics.income.source,/Unverified/);const missing=analyze({text:text+table.replace('USD in millions','')},'report.txt');assert.equal(missing.metrics.income.value,null)});
test('BM25 retrieves filing chunks by query relevance',()=>{const chunks=makeFilingChunks([{title:'Risk factors',source:'Item 1A',text:'Competition and customer concentration could adversely affect renewal rates and financial results. '.repeat(4)},{title:'Liquidity',source:'Item 7',text:'Cash equivalents, debt maturities, and revolving credit facilities support liquidity. '.repeat(4)},{title:'Financial facts',source:'Inline XBRL',text:'Revenue was $416.2b. Net income was $112.0b. Long-term debt was $90.7b. '.repeat(3)}],35,5);const results=retrieveBm25('customer concentration renewal risk',chunks,2);assert.ok(results.length>0);assert.equal(results[0].title,'Risk factors');assert.ok(results[0].score>0);assert.equal(retrieveBm25('sales',chunks,1)[0].title,'Financial facts');assert.equal(retrieveBm25('borrowing maturities',chunks,1)[0].title,'Liquidity');assert.deepEqual(retrieveBm25('the and of',chunks),[])});
test('grounded retrieval varies across repeated queries',()=>{const chunks=makeFilingChunks([{title:'Business overview',source:'Item 1',text:'The company designs smartphones, tablets, personal computers, wearables, and services for consumers. The iPhone is one product discussed in the filing.'},{title:'Risk factors',source:'Item 1A',text:'Competition, regulation, supply constraints, and economic conditions could adversely affect results.'},{title:'Financial facts',source:'Inline XBRL',text:'Revenue was $416.2b. Net income was $112.0b. Long-term debt was $90.7b.'}],35,5);assert.equal(retrieveGroundedChunks('what does the company sell',chunks,2)[0].title,'Business overview');assert.equal(retrieveGroundedChunks('iPhone',chunks,2)[0].title,'Business overview');assert.equal(retrieveGroundedChunks('revenue',chunks,2)[0].title,'Financial facts');assert.equal(retrieveGroundedChunks('what are the risks',chunks,2)[0].title,'Risk factors');assert.deepEqual(retrieveGroundedChunks('zyxwv qqqqq jargon',chunks,2),[])});
