'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Upload, FileText, ArrowRight, Check, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { analyze, readFile, demo, type Report, type MetricKey, labels, valueOf, valuation } from '@/lib/filing';
const LAMBDA_URL='https://zolnsjttd5k7ny7d6yhlf7v6cq0tcpfi.lambda-url.us-east-2.on.aws/';
const money = (n:number|null) => n === null ? '—' : '$'+n.toLocaleString('en-US',{maximumFractionDigits:1})+'m';
export default function Home(){
 useEffect(()=>{const input=document.querySelector('input[type="file"]') as HTMLInputElement|null;if(input){input.accept='application/pdf,.pdf';input.setAttribute('aria-label','Choose PDF 10-K file')}const copy=document.querySelector('.upload-copy p');if(copy)copy.textContent='PDF only · up to 30 MB · files stay in your browser';},[]);
 const [report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[drag,setDrag]=useState(false),[status,setStatus]=useState(''),[reviewed,setReviewed]=useState(false);
 const [low,setLow]=useState('15'),[high,setHigh]=useState('25'),[price,setPrice]=useState('');
 const input=useRef<HTMLInputElement>(null);
 async function upload(file?:File){if(!file||busy)return;setBusy(true);setError('');setStatus('Reading your filing…');try{const content=await readFile(file,setStatus);const next=analyze(content,file.name);const remote=await fetch(LAMBDA_URL,{method:'POST',headers:{'content-type':'application/pdf'},body:await file.arrayBuffer()});if(remote.ok){const data=await remote.json();next.notes=[...next.notes,'Python Lambda analysis completed.'];next.method=data.method||next.method;}setReport(next);setReviewed(false);setPrice('');setStatus('Analysis ready. Review the extracted figures below.');}catch(e){setError(e instanceof Error?e.message:'Unable to read this filing.');setStatus('');}finally{setBusy(false);}}
 function update(key:MetricKey,v:string){if(!report)return;setReport({...report,metrics:{...report.metrics,[key]:{...report.metrics[key],value:v===''?null:Number(v),manual:true}}});setReviewed(false);}
 const net=report?valueOf(report,'income'):null,rev=report?valueOf(report,'revenue'):null,shares=report?valueOf(report,'shares'):null;
 const range=valuation(net,shares,low,high), margin=net!==null&&rev!==null&&rev>0?net/rev*100:null;
 return <><header className="topbar"><a className="wordmark" href="https://isha-portfolio.vishaalsudarsan.chatgpt.site">Isha.</a><span className="appmark">FILING NOTES <span>/</span> 10-K ANALYZER</span><a className="back" href="https://isha-portfolio.vishaalsudarsan.chatgpt.site/#work">Back to portfolio <ArrowUpRight size={16}/></a></header>
 <main><div className="heading"><div><p className="eyebrow">RESEARCH, WITH A CLEARER VIEW</p><h1>From filing to <em>perspective.</em></h1><p className="intro">Understand the business. Review the numbers. Explore what it could be worth.</p></div><span className="edition">01 / FINANCIAL RESEARCH</span></div>
 <section className={'upload '+(drag?'drag':'')} aria-label="Upload annual filing" onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void upload(e.dataTransfer.files[0])}}><div className="upload-icon">{busy?<Loader2 className="spin"/>:<Upload/>}</div><div className="upload-copy"><h2>{busy?'Reading your 10-K…':'Drop a 10-K. Find the story.'}</h2><p>PDF, SEC HTML, or TXT · up to 30 MB · files stay in your browser</p></div><input ref={input} type="file" accept=".pdf,.html,.htm,.txt" aria-label="Choose 10-K file" hidden onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/><Button className="choose" disabled={busy} onClick={()=>input.current?.click()}>Choose filing <ArrowRight/></Button><Button variant="link" disabled={busy} onClick={()=>{setReport(demo());setReviewed(false);setPrice('');setError('');setStatus('Illustrative sample loaded.')}}>Try a sample</Button></section><p className="status" role="status">{status}</p>{error&&<p role="alert" className="error">{error}</p>}
 {!report?<section className="empty-layout"><div className="empty-title"><p className="eyebrow">YOUR RESEARCH DESK</p><h2>A long report.<br/>A focused view.</h2><p>Upload an annual filing to begin. SEC HTML with inline XBRL gives the most reliable financial extraction.</p></div><div className="steps">{[['01','The business at a glance','Business and risk excerpts drawn directly from the filing.'],['02','Financial fundamentals','Revenue, earnings, cash flow, and the source behind each figure.'],['03','A valuation you can question','An editable earnings-multiple range, with every assumption visible.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><h3>{t}</h3><p>{d}</p></section></div>)}</div></section>:<>
 <section className="report-heading"><div><p className="eyebrow">{report.sample?'ILLUSTRATIVE SAMPLE · NOT A REAL COMPANY':report.period?'FISCAL YEAR ENDED '+report.period:'UPLOADED ANNUAL FILING'}</p><h2>{report.company}</h2><p>{report.filename} · {report.method} · {Object.values(report.metrics).filter(m=>m.value!==null).length}/6 figures found</p></div><span className="badge"><FileText size={15}/> Research brief</span></section>
 <div className="metrics">{[['Revenue',money(rev)],['Net income',money(net)],['Net margin',margin===null?'—':margin.toFixed(1)+'%'],['Operating cash flow',money(valueOf(report,'cashflow'))]].map(([t,v])=><article key={t}><p>{t}</p><strong>{v}</strong><span>{t==='Net margin'?'Calculated from revenue and net income':'Reported fiscal year · USD'}</span></article>)}</div>
 <div className="dashboard"><div><section className="panel summary"><p className="eyebrow">01 / KEY SUMMARY</p><h2>The business, in brief.</h2>{report.notes.map((n,i)=><p className="note" key={i}>{n}</p>)}{report.excerpts.map((x,i)=><div className="excerpt" key={i}><h3>{x.title}</h3><p>{x.text}</p><span className="source">{x.source} · Extractive summary</span></div>)}</section>
 <section className="panel"><p className="eyebrow">02 / SOURCE FIGURES</p><h2>Review the fundamentals.</h2><p className="muted">All amounts and shares in millions. Confirm the fiscal period and units against your filing; edit any missing or incorrect figure.</p><div className="figure-list">{(Object.keys(labels) as MetricKey[]).map(key=><div className="figure" key={key}><div><label htmlFor={key}>{labels[key]}</label><p>{report.metrics[key].manual?'Edited by you':report.metrics[key].source||'Not found — enter from filing'}</p></div><Input id={key} type="number" step="any" value={report.metrics[key].value??''} placeholder="Missing" onChange={e=>update(key,e.target.value)}/></div>)}</div><Button variant="outline" className="review" onClick={()=>setReviewed(true)}><Check size={16}/>{reviewed?'Figures reviewed':'I have reviewed these figures'}</Button></section></div>
 <aside><section className="valuation"><p className="eyebrow">03 / VALUATION LENS</p><h2>What could it<br/>be worth?</h2><p>Explore an earnings-based equity value using your own P/E assumptions.</p><div className="range"><span>INDICATIVE VALUE PER SHARE</span><strong>{range&&!range.error?'$'+range.low.toFixed(2)+' – $'+range.high.toFixed(2):'Needs inputs'}</strong><small>{reviewed?'Based on your reviewed inputs':'Provisional · review source figures first'}</small></div><div className="scenario">{['low','high'].map((s,i)=><div key={s}><span>{i?'Upper case':'Lower case'}</span><div className="bar-track"><div style={{width:i?'100%':(Number(low)/Number(high)*100||0)+'%'}}/></div><strong>{i?high:low}× earnings</strong></div>)}</div><div className="assumptions"><label>Lower P/E multiple<Input type="number" min="1" step="1" value={low} onChange={e=>setLow(e.target.value)}/></label><label>Upper P/E multiple<Input type="number" min="1" step="1" value={high} onChange={e=>setHigh(e.target.value)}/></label></div><label className="price">Share price to compare (USD)<Input type="number" min="0.01" step="any" placeholder="Enter price manually" value={price} onChange={e=>setPrice(e.target.value)}/></label>{range?.error&&<p role="alert">{range.error}</p>}{range&&!range.error&&Number(price)>0&&<p className="comparison">{((range.low/Number(price)-1)*100).toFixed(1)}% to {((range.high/Number(price)-1)*100).toFixed(1)}% relative to your entered price.</p>}
 <details><summary>How this valuation works</summary><p>Equity value = net income × assumed P/E. Per-share value = equity value ÷ diluted weighted-average shares. The illustrative 15–25× defaults are not company-specific estimates or peer benchmarks. This model is unsuitable for losses and can be distorted by one-time earnings, debt, or dilution. Share price is entered manually; no live market data is used.</p><a href="https://pages.stern.nyu.edu/~adamodar/New_Home_Page/lectures/approach.html" target="_blank" rel="noreferrer">Valuation methodology · NYU Stern ↗</a></details></section><div className="aside-note"><span>READ THE CONTEXT</span><p>A valuation is a set of assumptions, not a price prediction. Use this research aid alongside the full filing.</p></div></aside></div></>}
 <footer><span className="wordmark">Isha.</span><p>Filing Notes · An independent research tool</p><span>Built for a closer look.</span></footer></main></>;
}
