'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Upload, FileText, ArrowRight, Check, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { analyze, readFile, demo, type Report, type MetricKey, labels, valueOf, valuation } from '@/lib/filing';
const DEFAULT_ANALYZER_API_URL='https://zolnsjttd5k7ny7d6yhlf7v6cq0tcpfi.lambda-url.us-east-2.on.aws/';
const LAMBDA_URL=import.meta.env.VITE_ANALYZER_API_URL||import.meta.env.NEXT_PUBLIC_ANALYZER_API_URL||DEFAULT_ANALYZER_API_URL;
const DEFAULT_FILING_URL='https://d18rn0p25nwr6d.cloudfront.net/CIK-0000320193/c636d8a7-8025-47d2-9b13-bcf5465343b3.html';
const DEFAULT_COMPANY='Apple';
const DEFAULT_YEAR='2025';
const money = (n:number|null) => {
 if(n===null)return '—';
 const abs=Math.abs(n);
 return abs>=1000?'$'+(n/1000).toLocaleString('en-US',{maximumFractionDigits:1})+'b':'$'+n.toLocaleString('en-US',{maximumFractionDigits:1})+'m';
};
type LambdaMetrics={revenue?:number;cost_of_revenue?:number;gross_profit?:number;operating_expenses?:number;operating_income?:number;net_income?:number;diluted_eps?:number;operating_cash_flow?:number;capex?:number;free_cash_flow?:number;capital_return?:number;cash?:number;total_assets?:number;total_liabilities?:number;long_term_debt?:number;shareholders_equity?:number;shares?:number};
type LambdaSections={business?:string;risk_factors?:string;document?:string};
type LambdaResponse={error?:string;company?:string;period?:string;method?:string;metrics?:LambdaMetrics;sections?:LambdaSections};
type AnalyzePayload={url?:string;company?:string;year?:string};
const remoteMetricMap:Record<keyof LambdaMetrics,MetricKey>={revenue:'revenue',cost_of_revenue:'costOfRevenue',gross_profit:'grossProfit',operating_expenses:'operatingExpenses',operating_income:'operatingIncome',net_income:'income',diluted_eps:'dilutedEps',operating_cash_flow:'cashflow',capex:'capex',free_cash_flow:'freeCashFlow',capital_return:'capitalReturn',cash:'cash',total_assets:'assets',total_liabilities:'liabilities',long_term_debt:'debt',shareholders_equity:'equity',shares:'shares'};
const emptyMetrics=():Report['metrics']=>Object.fromEntries(Object.keys(labels).map(key=>[key,{value:null,source:''}])) as Report['metrics'];
function applyRemoteMetrics(report:Report,data:LambdaResponse,sourceLabel:string){for(const [source,target] of Object.entries(remoteMetricMap) as [keyof LambdaMetrics,MetricKey][]){const value=data.metrics?.[source];if(typeof value==='number')report.metrics[target]={value,source:sourceLabel};}}
function remoteExcerpts(data:LambdaResponse):Report['excerpts']{const excerpts:Report['excerpts']=[];if(data.sections?.business)excerpts.push({title:'',text:data.sections.business,source:'Item 1. Business'});if(data.sections?.risk_factors)excerpts.push({title:'Risk factors.',text:data.sections.risk_factors,source:'Item 1A. Risk Factors'});return excerpts;}
function sentences(text:string){return text.split(/(?<=[.!?])\s+/).map(s=>s.trim()).filter(Boolean);}
const dollarMetric=(key:MetricKey)=>key!=='shares';
const displayScale=(key:MetricKey,value:number|null)=>dollarMetric(key)&&value!==null&&Math.abs(value)>=1000?1000:1;
const displayUnit=(key:MetricKey,value:number|null)=>key==='shares'?'millions':displayScale(key,value)===1000?'USD billions':'USD millions';
type FundamentalEntry={label:string;metric?:MetricKey;detail:string;deduct?:boolean;hideWhenMissing?:boolean};
const fundamentals:{title:string;caption:string;entries:FundamentalEntry[]}[]=[
 {title:'Income statement',caption:'Revenue and earnings power',entries:[{label:'Revenue / net sales',metric:'revenue',detail:'Top-line sales for the fiscal year'},{label:'Cost of revenue / cost of sales',metric:'costOfRevenue',detail:'Direct cost of goods or services sold',deduct:true,hideWhenMissing:true},{label:'Gross profit',metric:'grossProfit',detail:'Revenue less cost of revenue',hideWhenMissing:true},{label:'Operating expenses',metric:'operatingExpenses',detail:'Total operating expense line item',deduct:true},{label:'Operating income',metric:'operatingIncome',detail:'Income from operations'},{label:'Net income',metric:'income',detail:'Profit attributable to common shareholders'},{label:'Diluted EPS',metric:'dilutedEps',detail:'Earnings per diluted share'}]},
 {title:'Balance sheet',caption:'Liquidity, assets, and capital structure',entries:[{label:'Cash and cash equivalents',metric:'cash',detail:'Reported cash balance'},{label:'Total assets',metric:'assets',detail:'Total assets at period end'},{label:'Total debt / long-term debt',metric:'debt',detail:'Debt balance currently available'},{label:'Total liabilities',metric:'liabilities',detail:'Total liabilities at period end'},{label:'Shareholders’ equity',metric:'equity',detail:'Reported stockholders’ equity'},{label:'Diluted shares outstanding',metric:'shares',detail:'Weighted-average diluted shares'}]},
 {title:'Cash flow',caption:'Cash generation and capital return',entries:[{label:'Operating cash flow',metric:'cashflow',detail:'Cash from operations'},{label:'Capital expenditures',metric:'capex',detail:'Purchases of property, plant and equipment',deduct:true},{label:'Free cash flow',metric:'freeCashFlow',detail:'Operating cash flow less capital expenditures'},{label:'Share repurchases / dividends',metric:'capitalReturn',detail:'Cash returned through buybacks and dividends',deduct:true}]},
];
function fundamentalValue(report:Report,entry:FundamentalEntry){if(!entry.metric)return '—';const value=valueOf(report,entry.metric);if(value===null)return '—';let formatted=entry.metric==='shares'?value.toLocaleString('en-US',{maximumFractionDigits:1})+'m':entry.metric==='dilutedEps'?'$'+value.toLocaleString('en-US',{maximumFractionDigits:2}):money(value);return entry.deduct?'('+formatted+')':formatted;}
function fundamentalSource(report:Report,entry:FundamentalEntry){if(!entry.metric)return entry.detail;const metric=report.metrics[entry.metric];return metric.value===null?'Not separately reported in this filing':entry.detail;}
function visibleFundamentalEntries(report:Report,entries:FundamentalEntry[]){return entries.filter(entry=>!entry.hideWhenMissing||!entry.metric||valueOf(report,entry.metric)!==null);}
export default function Home(){
 useEffect(()=>{document.querySelector('.upload')?.remove();},[]);
 const [report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[drag,setDrag]=useState(false),[status,setStatus]=useState(''),[reviewed,setReviewed]=useState(false);
 const [low,setLow]=useState('15'),[high,setHigh]=useState('25'),[price,setPrice]=useState(''),[filingUrl,setFilingUrl]=useState(DEFAULT_FILING_URL);
 const [companyQuery,setCompanyQuery]=useState(DEFAULT_COMPANY),[filingYear,setFilingYear]=useState(DEFAULT_YEAR);
 const [activeFundamental,setActiveFundamental]=useState(0);
 const input=useRef<HTMLInputElement>(null);
 async function runAnalysis(payload:AnalyzePayload,filename:string){if(busy)return;setBusy(true);setError('');setStatus('Fetching SEC filing…');try{const res=await fetch(LAMBDA_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await res.json() as LambdaResponse;if(!res.ok)throw Error(data.error||'Unable to analyze filing.');const next:Report={company:data.company||'Company name not found',period:data.period||'',filename,method:'SEC HTML extraction',metrics:emptyMetrics(),notes:['Analysis returned from SEC filing extraction.'],excerpts:remoteExcerpts(data)};applyRemoteMetrics(next,data,'SEC filing · inline XBRL');setReport(next);setReviewed(false);setPrice('');setStatus('Analysis ready. Review the extracted figures below.');}catch(e){setError(e instanceof Error?e.message:'Unable to analyze filing.');setStatus('');}finally{setBusy(false);}}
 async function analyzeCompany(){if(!companyQuery||!filingYear||busy)return;await runAnalysis({company:companyQuery,year:filingYear},`${companyQuery} · ${filingYear} 10-K`);}
 async function analyzeUrl(){if(!filingUrl||busy)return;await runAnalysis({url:filingUrl},filingUrl);}
 async function upload(file?:File){if(!file||busy)return;setBusy(true);setError('');setStatus('Reading your filing…');try{const content=await readFile(file,setStatus);const next=analyze(content,file.name);const remote=await fetch(LAMBDA_URL,{method:'POST',headers:{'content-type':'application/pdf'},body:await file.arrayBuffer()});if(remote.ok){const data=await remote.json() as LambdaResponse;applyRemoteMetrics(next,data,'SEC filing extraction');next.excerpts=[...remoteExcerpts(data),...next.excerpts];next.notes=[...next.notes,'SEC filing analysis completed.'];next.method=data.method||next.method;}setReport(next);setReviewed(false);setPrice('');setStatus('Analysis ready. Review the extracted figures below.');}catch(e){setError(e instanceof Error?e.message:'Unable to read this filing.');setStatus('');}finally{setBusy(false);}}
 function update(key:MetricKey,v:string){if(!report)return;const current=report.metrics[key].value,scale=displayScale(key,current);setReport({...report,metrics:{...report.metrics,[key]:{...report.metrics[key],value:v===''?null:Number(v)*scale,manual:true}}});setReviewed(false);}
 const net=report?valueOf(report,'income'):null,rev=report?valueOf(report,'revenue'):null,shares=report?valueOf(report,'shares'):null;
 const range=valuation(net,shares,low,high), margin=net!==null&&rev!==null&&rev>0?net/rev*100:null;
 const activeStatement=fundamentals[activeFundamental]||fundamentals[0];
 const activeStatementEntries=report?visibleFundamentalEntries(report,activeStatement.entries):activeStatement.entries;
 return <><header className="topbar"><a className="wordmark" href="https://isha-portfolio.vishaalsudarsan.chatgpt.site">Isha.</a><span className="appmark">FILING NOTES <span>/</span> 10-K ANALYZER</span><a className="back" href="https://isha-portfolio.vishaalsudarsan.chatgpt.site/#work">Back to portfolio <ArrowUpRight size={16}/></a></header>
 <main><div className="heading"><div><p className="eyebrow">RESEARCH, WITH A CLEARER VIEW</p><h1>From filing to <em>perspective.</em></h1><p className="intro">Understand the business. Review the numbers. Explore what it could be worth.</p></div><span className="edition">01 / FINANCIAL RESEARCH</span></div>
 <div className="lookup-form"><div><label htmlFor="company-query">Company or ticker</label><input id="company-query" value={companyQuery} onChange={e=>setCompanyQuery(e.target.value)} placeholder="Apple, JPM, TSLA" aria-label="Company or ticker"/></div><div><label htmlFor="filing-year">Fiscal year</label><input id="filing-year" value={filingYear} onChange={e=>setFilingYear(e.target.value)} placeholder="2025" aria-label="Fiscal year"/></div><button onClick={()=>void analyzeCompany()} disabled={busy||!companyQuery||!filingYear}>Find 10-K</button></div><details className="url-details"><summary>Use a filing URL instead</summary><div className="url-form"><input value={filingUrl} onChange={e=>setFilingUrl(e.target.value)} placeholder="Paste SEC filing HTML URL" aria-label="SEC filing URL"/><button onClick={()=>void analyzeUrl()} disabled={busy||!filingUrl}>Analyze URL</button></div></details><section className={'upload '+(drag?'drag':'')} aria-label="Upload annual filing" onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void upload(e.dataTransfer.files[0])}}><div className="upload-icon">{busy?<Loader2 className="spin"/>:<Upload/>}</div><div className="upload-copy"><h2>{busy?'Reading your 10-K…':'Drop a 10-K. Find the story.'}</h2><p>PDF, SEC HTML, or TXT · up to 30 MB · files stay in your browser</p></div><input ref={input} type="file" accept=".pdf,.html,.htm,.txt" aria-label="Choose 10-K file" hidden onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/><Button className="choose" disabled={busy} onClick={()=>input.current?.click()}>Choose filing <ArrowRight/></Button><Button variant="link" disabled={busy} onClick={()=>{setReport(demo());setReviewed(false);setPrice('');setError('');setStatus('Illustrative sample loaded.')}}>Try a sample</Button></section><p className="status" role="status">{status}</p>{error&&<p role="alert" className="error">{error}</p>}
 {!report?<section className="empty-layout"><div className="empty-title"><p className="eyebrow">YOUR RESEARCH DESK</p><h2>A long report.<br/>A focused view.</h2><p>Upload an annual filing to begin. SEC HTML with inline XBRL gives the most reliable financial extraction.</p></div><div className="steps">{[['01','The business at a glance','Business and risk excerpts drawn directly from the filing.'],['02','Financial fundamentals','Revenue, earnings, cash flow, and the source behind each figure.'],['03','A valuation you can question','An editable earnings-multiple range, with every assumption visible.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><h3>{t}</h3><p>{d}</p></section></div>)}</div></section>:<>
 <section className="report-heading"><div><p className="eyebrow">{report.sample?'ILLUSTRATIVE SAMPLE · NOT A REAL COMPANY':report.period?'FISCAL YEAR ENDED '+report.period:'UPLOADED ANNUAL FILING'}</p><h2>{report.company}</h2></div><span className="badge"><FileText size={15}/> Research brief</span></section>
 <div className="metrics">{[['Revenue',money(rev)],['Net income',money(net)],['Net margin',margin===null?'—':margin.toFixed(1)+'%'],['Operating cash flow',money(valueOf(report,'cashflow'))]].map(([t,v])=><article key={t}><p>{t}</p><strong>{v}</strong><span>{t==='Net margin'?'Calculated from revenue and net income':'Reported fiscal year · USD'}</span></article>)}</div>
 <div className="dashboard"><div>{report.excerpts.length>0&&<section className="panel summary"><p className="eyebrow">01 / BUSINESS OVERVIEW</p><h2>The business, in brief.</h2>{report.excerpts.map((x,i)=><div className="excerpt" key={i}>{x.title&&<h3>{x.title}</h3>}{x.source.includes('Risk Factors')?<ul className="risk-list">{sentences(x.text).map((sentence,j)=><li key={j}>{sentence}</li>)}</ul>:<p>{x.text}</p>}</div>)}</section>}<section className="panel fundamentals-panel"><p className="eyebrow">02 / SOURCE FIGURES</p><h2>Review the fundamentals.</h2><p className="muted">A statement-level snapshot from the filing. Large dollar amounts are shown in billions; shares are shown in millions.</p><div className="statement-tabs" role="tablist" aria-label="Financial statement view">{fundamentals.map((section,i)=><button key={section.title} type="button" role="tab" aria-selected={activeFundamental===i} className={activeFundamental===i?'active':''} onClick={()=>setActiveFundamental(i)}>{section.title}</button>)}</div><article className="statement" role="tabpanel"><div className="statement-head"><h3>{activeStatement.title}</h3><span>{activeStatement.caption}</span></div><div className="statement-lines">{activeStatementEntries.map(entry=><div className="statement-line" key={entry.label}><div><strong>{entry.label}</strong><p>{fundamentalSource(report,entry)}</p></div><span className={entry.deduct?'deduct':''}>{fundamentalValue(report,entry)}</span></div>)}</div></article></section></div>
 <aside><section className="valuation"><p className="eyebrow">03 / VALUATION LENS</p><h2>What could it<br/>be worth?</h2><p>Explore an earnings-based equity value using your own P/E assumptions.</p><div className="range"><span>INDICATIVE VALUE PER SHARE</span><strong>{range&&!range.error?'$'+range.low.toFixed(2)+' – $'+range.high.toFixed(2):'Needs inputs'}</strong><small>{reviewed?'Based on your reviewed inputs':'Provisional · review source figures first'}</small></div><div className="scenario">{['low','high'].map((s,i)=><div key={s}><span>{i?'Upper case':'Lower case'}</span><div className="bar-track"><div style={{width:i?'100%':(Number(low)/Number(high)*100||0)+'%'}}/></div><strong>{i?high:low}× earnings</strong></div>)}</div><div className="assumptions"><label>Lower P/E multiple<Input type="number" min="1" step="1" value={low} onChange={e=>setLow(e.target.value)}/></label><label>Upper P/E multiple<Input type="number" min="1" step="1" value={high} onChange={e=>setHigh(e.target.value)}/></label></div><label className="price">Share price to compare (USD)<Input type="number" min="0.01" step="any" placeholder="Enter price manually" value={price} onChange={e=>setPrice(e.target.value)}/></label>{range?.error&&<p role="alert">{range.error}</p>}{range&&!range.error&&Number(price)>0&&<p className="comparison">{((range.low/Number(price)-1)*100).toFixed(1)}% to {((range.high/Number(price)-1)*100).toFixed(1)}% relative to your entered price.</p>}
 <details><summary>How this valuation works</summary><p>Equity value = net income × assumed P/E. Per-share value = equity value ÷ diluted weighted-average shares. The illustrative 15–25× defaults are not company-specific estimates or peer benchmarks. This model is unsuitable for losses and can be distorted by one-time earnings, debt, or dilution. Share price is entered manually; no live market data is used.</p><a href="https://pages.stern.nyu.edu/~adamodar/New_Home_Page/lectures/approach.html" target="_blank" rel="noreferrer">Valuation methodology · NYU Stern ↗</a></details></section><div className="aside-note"><span>READ THE CONTEXT</span><p>A valuation is a set of assumptions, not a price prediction. Use this research aid alongside the full filing.</p></div></aside></div></>}
 <footer><span className="wordmark">Isha.</span><p>Filing Notes · An independent research tool</p><span>Built for a closer look.</span></footer></main></>;
}
