export const labels={revenue:'Revenue',costOfRevenue:'Cost of revenue',grossProfit:'Gross profit',operatingExpenses:'Operating expenses',operatingIncome:'Operating income',income:'Net income',dilutedEps:'Diluted EPS',cashflow:'Operating cash flow',capex:'Capital expenditures',freeCashFlow:'Free cash flow',capitalReturn:'Share repurchases / dividends',cash:'Cash & equivalents',assets:'Total assets',liabilities:'Total liabilities',debt:'Long-term debt (noncurrent)',equity:'Shareholders’ equity',shares:'Diluted weighted-average shares',employees:'Employees'};
export type MetricKey=keyof typeof labels;
type Metric={value:number|null;source:string;manual?:boolean};
export type Report={company:string;period:string;filename:string;method:string;sample?:boolean;metrics:Record<MetricKey,Metric>;notes:string[];excerpts:{title:string;text:string;source:string}[]};
export type Content={text:string;html?:string};
const tags:Partial<Record<MetricKey,string[]>>={revenue:['RevenueFromContractWithCustomerExcludingAssessedTax','Revenues','SalesRevenueNet','RevenueFromContractWithCustomerIncludingAssessedTax'],costOfRevenue:['CostOfRevenue','CostOfGoodsAndServicesSold','CostOfGoodsSold'],grossProfit:['GrossProfit'],operatingExpenses:['OperatingExpenses'],operatingIncome:['OperatingIncomeLoss'],income:['NetIncomeLoss','ProfitLoss'],dilutedEps:['EarningsPerShareDiluted'],cashflow:['NetCashProvidedByUsedInOperatingActivities'],capex:['PaymentsToAcquirePropertyPlantAndEquipment'],capitalReturn:['PaymentsForRepurchaseOfCommonStock','PaymentsForRepurchaseOfEquity','PaymentsOfDividends','PaymentsOfDividendsCommonStock','PaymentsOfOrdinaryDividends'],cash:['CashAndCashEquivalentsAtCarryingValue'],assets:['Assets'],liabilities:['Liabilities'],debt:['LongTermDebtNoncurrent','LongTermDebt'],equity:['StockholdersEquity','StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest'],shares:['WeightedAverageNumberOfDilutedSharesOutstanding']};
const instantMetrics=new Set<MetricKey>(['cash','assets','liabilities','debt','equity']);
const perShareMetrics=new Set<MetricKey>(['dilutedEps']);
const number=(s:string)=>{const cleaned=s.replace(/[$,\s]/g,'');if(!/^\(?-?\d+(\.\d+)?\)?$/.test(cleaned))return null;const n=Number(cleaned.replace(/[()]/g,''))*(cleaned.includes('(')?-1:1);return Number.isFinite(n)?n:null};
const local=(el:Element)=>el.tagName.toLowerCase().split(':').pop();
function descendants(el:Element|Document,name:string){return Array.from(el.querySelectorAll('*')).filter(e=>local(e)===name.toLowerCase())}
export async function readFile(file:File,progress:(s:string)=>void):Promise<Content>{
 if(file.size>30*1024*1024)throw Error('This file exceeds 30 MB. Choose a smaller filing.');
 const ext=file.name.split('.').pop()?.toLowerCase();if(ext!=='pdf'||(file.type&&file.type!=='application/pdf'))throw Error('Choose a PDF 10-K file.');
 if(ext==='pdf'){
 const pdfjs=await import('pdfjs-dist');
 // Resolve the worker from the deployed site origin. Bundler-generated file:// URLs
 // cannot be fetched by browsers in production.
 pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';
 const task=pdfjs.getDocument({data:await file.arrayBuffer()});let pdf;try{pdf=await task.promise;const pages:string[]=[];if(pdf.numPages>1200)throw Error('This PDF has too many pages. Choose the annual report without exhibits.');for(let i=1;i<=pdf.numPages;i++){progress('Reading page '+i+' of '+pdf.numPages+'…');const page=await pdf.getPage(i);const content=await page.getTextContent();let lastY:number|null=null;let line='';const lines:string[]=[];for(const item of content.items){if(!('str' in item))continue;const y=item.transform[5];if(lastY!==null&&Math.abs(lastY-y)>3){lines.push(line);line=''}line+=' '+item.str;lastY=y;if(item.hasEOL){lines.push(line);line='';lastY=null}}if(line)lines.push(line);pages.push('[Page '+i+']\n'+lines.join('\n'));page.cleanup()}return {text:pages.join('\n')};}catch(e){if(e instanceof Error&&e.name==='PasswordException')throw Error('This PDF is password protected. Upload an unlocked copy.');throw e;}finally{await task.destroy();}
 }
 const raw=await file.text();if(ext==='html'||ext==='htm'){const doc=new DOMParser().parseFromString(raw,'text/html');doc.querySelectorAll('script,style,iframe,object,link,img').forEach(e=>e.remove());const html=doc.documentElement.outerHTML;doc.querySelectorAll('tr,p,div,br,h1,h2,h3').forEach(e=>e.append('\n'));descendants(doc,'hidden').forEach(e=>e.remove());return {text:doc.body.textContent||'',html};}return {text:raw};
}
export function analyze(content:Content,filename:string):Report{
 const text=content.text.replace(/\u00a0/g,' ');if(text.trim().length<300)throw Error('Not enough readable text. Scanned PDFs need OCR first; try the SEC HTML version.');if(!/10[\s–-]?k\b|annual report/i.test(text))throw Error('This does not appear to be a 10-K or annual report. Please choose an annual filing.');
 const metrics=Object.fromEntries(Object.keys(labels).map(k=>[k,{value:null,source:''}])) as Report['metrics'];let period='',company=filename.replace(/\.[^.]+$/,'');let count=0;
 if(content.html){const doc=new DOMParser().parseFromString(content.html,'text/html');const facts=Array.from(doc.querySelectorAll('*')).filter(e=>e.hasAttribute('name')&&e.hasAttribute('contextref'));const factText=(name:string)=>facts.find(e=>e.getAttribute('name')?.split(':').pop()===name)?.textContent?.trim()||'';period=factText('DocumentPeriodEndDate');company=factText('EntityRegistrantName')||company;
 const contexts=new Map(descendants(doc,'context').map(c=>[c.id,c]));
 for(const key of Object.keys(tags) as MetricKey[]){const metricTags=tags[key]||[];const candidates=facts.flatMap(f=>{const tag=f.getAttribute('name')?.split(':').pop()||'';if(!metricTags.includes(tag))return [];const c=contexts.get(f.getAttribute('contextref')||'');if(!c||descendants(c,'explicitmember').length||descendants(c,'typedmember').length)return [];const end=descendants(c,'enddate')[0]?.textContent||descendants(c,'instant')[0]?.textContent||'';const start=descendants(c,'startdate')[0]?.textContent||'';const days=(Date.parse(end)-Date.parse(start))/86400000;const instant=instantMetrics.has(key);if(instant?!!start:!(days>=330&&days<=380))return [];if(period&&end!==period)return [];const unitId=f.getAttribute('unitref');const unit=unitId?doc.getElementById(unitId):null;const measures=unit?descendants(unit,'measure').map(e=>e.textContent?.split(':').pop()?.toUpperCase()):[];const expectedUnit=key==='shares'?'SHARES':perShareMetrics.has(key)?'PURE':'USD';if(!measures.includes(expectedUnit))return [];let value=number(f.textContent||'');if(value===null||f.getAttribute('format')?.includes('zerodash'))return [];value*=10**Number(f.getAttribute('scale')||0);if(f.getAttribute('sign')==='-')value=-Math.abs(value);if(!perShareMetrics.has(key))value/=1e6;if(['capex','capitalReturn'].includes(key))value=Math.abs(value);if(!Number.isFinite(value))return [];return [{value,end,tag,priority:metricTags.indexOf(tag)}]}).sort((a,b)=>b.end.localeCompare(a.end)||a.priority-b.priority);
 const best=candidates[0];if(best){const conflicts=candidates.filter(c=>c.end===best.end&&c.tag===best.tag).some(c=>Math.abs(c.value-best.value)>0.01);if(!conflicts){metrics[key]={value:best.value,source:best.tag+' · '+best.end+' · normalized to millions'};count++}}
 }
 }
 const lines=text.split(/\n/).map(s=>s.replace(/\s+/g,' ').trim()).filter(Boolean);
 let textCount=0;
 const rowPatterns:Partial<Record<MetricKey,RegExp>>={revenue:/^(?:total\s+)?(?:net\s+)?(?:revenues?|net sales)\s*[:$]?\s+/i,costOfRevenue:/^(?:cost of (?:revenue|sales)|cost of goods (?:sold|and services sold))\s*[:$]?\s+/i,grossProfit:/^gross profit\s*[:$]?\s+/i,operatingExpenses:/^(?:total )?operating expenses\s*[:$]?\s+/i,operatingIncome:/^operating income(?:\s*\(loss\))?\s*[:$]?\s+/i,income:/^net (?:income|earnings)(?:\s*\(loss\))?\s*[:$]?\s+/i,cashflow:/^net cash (?:provided by|from|provided by \(used in\)|provided by \(used for\)) operating activities\s*[:$]?\s+/i,capex:/^(?:payments for|purchases of|capital expenditures for|acquisition of) (?:property,? plant and equipment|property and equipment)\s*[:$]?\s+/i,cash:/^cash and cash equivalents\s*[:$]?\s+/i,assets:/^total assets\s*[:$]?\s+/i,liabilities:/^total liabilities\s*[:$]?\s+/i,debt:/^long[–-]term debt(?:,? net of current (?:portion|maturities))?\s*[:$]?\s+/i,equity:/^(?:total )?(?:shareholders’|shareholders'|stockholders’|stockholders') equity\s*[:$]?\s+/i,shares:/^(?:weighted[–-]average diluted shares(?: outstanding)?|diluted weighted[–-]average (?:common )?shares(?: outstanding)?)\s*[:$]?\s+/i};
 for(const key of Object.keys(labels) as MetricKey[]){if(metrics[key].value!==null||!rowPatterns[key])continue;const hits:{value:number;source:string}[]=[];for(let i=0;i<lines.length;i++){const match=lines[i].match(rowPatterns[key]);if(!match)continue;const before=lines.slice(Math.max(0,i-45),i).join(' ');if(!/consolidated (?:statements|balance|cash flows)/i.test(before))continue;const units=[...before.matchAll(/(?:in |\()\s*(millions|thousands|billions)/gi)].pop()?.[1]?.toLowerCase();if(!units||!/\$|USD|U\.S\. dollars/i.test(before+' '+lines[i]))continue;const years=[...before.matchAll(/\b(20\d{2})\b/g)].map(m=>m[1]);const columns=years.slice(-3);const year=columns[0];if(columns.length<2||!columns.every((y,j)=>j===0||y<columns[j-1]))continue;const row=lines[i].slice(match[0].length);const values=row.match(/\(?-?\d[\d,]*(?:\.\d+)?\)?/g);if(!values||values.length<2)continue;const amount=number(values[0]);if(amount===null)continue;const scale=units==='billions'?1000:units==='thousands'?.001:1;hits.push({value:amount*scale,source:'Unverified table candidate · '+year+' · '+units+' · '+lines[i].slice(0,160)});}
 if(hits.length&&hits.every(h=>h.value===hits[0].value)){metrics[key]=hits[0];textCount++;}
 }
 if(metrics.cashflow.value!==null&&metrics.capex.value!==null)metrics.freeCashFlow={value:metrics.cashflow.value-metrics.capex.value,source:'Calculated from operating cash flow minus capital expenditures'};
 const notes:string[]=[];if(!count&&!textCount)notes.push('Financial figures could not be reliably verified. Enter the source figures below to calculate valuation.');else if(count)notes.push('Extracted '+count+' consolidated annual figures from inline XBRL. Confirm these figures against the financial statements before using the valuation.');
 if(metrics.revenue.value!==null&&metrics.income.value!==null&&metrics.revenue.value>0)notes.push('The company reported a '+(metrics.income.value/metrics.revenue.value*100).toFixed(1)+'% net margin for the reported annual period.');
 if(metrics.income.value!==null&&metrics.income.value<=0)notes.push('Net income is not positive. An earnings-multiple valuation is not meaningful for this period.');
 if(textCount)notes.push(textCount+' figures are unverified table candidates. Check column order, currency, fiscal year, and units before using them.');
 const excerpts:Report['excerpts']=[];
 for(const [title,pattern] of [['Business overview',/item\s*1[.\s:–-]+business/i],['Key risks',/item\s*1a[.\s:–-]+risk factors/i],['Management’s discussion',/item\s*7[.\s:–-]+management/i]] as [string,RegExp][]){const indices=lines.map((s,i)=>pattern.test(s)?i:-1).filter(i=>i>=0);let selected=-1;for(const i of indices){const next=lines.slice(i+1,i+12).join(' ');if(next.length>300&&!/^item\s*\d/i.test(next)){selected=i;}}
 if(selected>=0){const parts:string[]=[];for(let i=selected+1;i<lines.length&&parts.join(' ').length<1100;i++){if(/^item\s*\d+[a-z]?[.\s]/i.test(lines[i]))break;if(!/^\[Page|^\d+$|^table of contents$/i.test(lines[i]))parts.push(lines[i]);}let excerpt=parts.join(' ');if(excerpt.length>850){const stop=excerpt.lastIndexOf('. ',850);excerpt=excerpt.slice(0,stop>300?stop+1:850)+'…';}if(excerpt.length>80){const page=lines.slice(0,selected+1).reverse().find(s=>/^\[Page \d+\]/.test(s));excerpts.push({title,text:excerpt,source:page?page+' · '+lines[selected].slice(0,90):lines[selected].slice(0,120)})}}
 }
 if(!excerpts.length){const substantial=lines.filter(s=>s.length>180&&!/table of contents/i.test(s)).slice(0,2);excerpts.push(...substantial.map(s=>({title:'Filing excerpt',text:s.slice(0,850)+(s.length>850?'…':''),source:'Uploaded document · section not identified'})));notes.push('Section headings were not reliably identified. Read the full filing for business context and risks.');}
 return {company,period,filename,method:count?'Inline XBRL extraction':textCount?'Text extraction · unverified table candidates':'Text extraction · manual financial review',metrics,notes,excerpts};
}
export function valueOf(r:Report,key:MetricKey){const v=r.metrics[key].value;return v!==null&&Number.isFinite(v)?v:null}
export function valuation(income:number|null,shares:number|null,low:string,high:string){const l=Number(low),h=Number(high);if(income===null||shares===null)return null;if(!Number.isFinite(income)||!Number.isFinite(shares)||income<=0||shares<=0)return {low:0,high:0,error:'Positive net income and diluted shares are required.'};if(!Number.isFinite(l)||!Number.isFinite(h)||l<=0||h<l||h>200)return {low:0,high:0,error:'Use positive P/E multiples in ascending order, up to 200×.'};return {low:income/shares*l,high:income/shares*h,error:''}}
export function demo():Report{return {company:'Northstar Systems, Inc.',period:'2025-12-31',filename:'Illustrative 10-K',method:'Fictional demonstration',sample:true,metrics:{revenue:{value:8420,source:'Illustrative income statement · FY2025'},costOfRevenue:{value:3610,source:'Illustrative income statement · FY2025'},grossProfit:{value:4810,source:'Illustrative income statement · FY2025'},operatingExpenses:{value:3040,source:'Illustrative income statement · FY2025'},operatingIncome:{value:1770,source:'Illustrative income statement · FY2025'},income:{value:1263,source:'Illustrative income statement · FY2025'},dilutedEps:{value:6,source:'Illustrative income statement · FY2025'},cashflow:{value:1710,source:'Illustrative cash flow statement · FY2025'},capex:{value:420,source:'Illustrative cash flow statement · FY2025'},freeCashFlow:{value:1290,source:'Illustrative operating cash flow less capital expenditures'},capitalReturn:{value:760,source:'Illustrative cash flow statement · FY2025'},cash:{value:2340,source:'Illustrative balance sheet · FY2025'},assets:{value:12450,source:'Illustrative balance sheet · FY2025'},liabilities:{value:6410,source:'Illustrative balance sheet · FY2025'},debt:{value:1850,source:'Illustrative balance sheet · FY2025'},equity:{value:6040,source:'Illustrative balance sheet · FY2025'},shares:{value:210.5,source:'Illustrative EPS note · FY2025'},employees:{value:3200,source:'Illustrative human capital disclosure · FY2025'}},notes:['This is fictional sample data to explore the dashboard. Upload a real filing to analyze a company.','Illustrative annual revenue is $8,420 million, with a 15.0% net margin.'],excerpts:[{title:'Business overview',text:'Northstar Systems is a fictional enterprise software company providing cloud infrastructure and workflow tools. Subscription contracts account for most sales, supported by implementation and consulting services.',source:'Sample · Item 1. Business'},{title:'Key risks',text:'The illustrative business faces competition from larger cloud providers, customer concentration, and higher infrastructure costs. Its recurring revenue depends on contract renewals and the continued reliability of its platforms.',source:'Sample · Item 1A. Risk factors'}]}}
